[project]
name = "meegnet_lamaroufle"
version = "0.1.0"
authors = [
  { name="Arthur Dehgan", email="arthurdehgan@hotmail.com" },
]
description = ""
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/arthurdehgan/meegnet"
