config = "eventclf.toml"
root_table = ""
flat = false
epoched = true
randomsearch = false
net_option = "best_net"
datatype = "passive"
eventclf = true
subclf = false
crossval = false
filters = 8
sfreq = 500
maxpool = 0
batchnorm = false
permute_labels = false
printmem = false
log = true
lr = 1e-5
hlayers = 1
patience = 20
model_name = "best_net"
num_workers = 4
train_size = 0.8
save_path = "/home/arthur/data/camcan/eventclf/"
raw_path = "/home/arthur/disk/camcan"
seed = 42
max_subj = 300
age_min = 1
age_max = 100
clf_type = ""
sensors = "MAG"
feature = "temporal"
batch_size = 128
dropout = 0.25
times = false
chunkload = false
debug = false
dropout_option = "same"
linear = 100
mode = "continue"
nchan = 100
compute_psd = false
w_size = 300
confidence = 0.98
saliency_type = "sum"
